### ISSUE TITLE
latest baseball databank release doesn't include 2018 stats

### ISSUE THREAD

**Issue by rusmo** [rippinrobr/baseball-databank-scripts#35]
Just downloaded postgres_databank_backup_2018.01.tgz from the releases page, and ran the contained SQL. the latest yearID I was able to find in the batting and pitching tables is 2017. The post on the releases page says it had been updated to include 2018 stats. Any chance you can update the release to include 2018 stats?

Thanks.

**Comment by rippinrobr** [comment]
Yes, I will, tonight I will run an update and push up the latest baseball databank update.  When it's up I'll update this ticket.

**Comment by rippinrobr** [comment]
@rusmo the latest data has been loaded and released.  You can grab it from here https://github.com/rippinrobr/baseball-stats-db/releases/tag/2018.02  Let me know if you have any questions.

**Comment by rusmo** [comment]
Got it, thanks!
